sonar.projectKey=somethingwithproof_stonktop
sonar.organization=somethingwithproof

sonar.sources=src
sonar.tests=tests

sonar.rust.clippyReport.reportPaths=clippy.json
sonar.rust.lcov.reportPaths=lcov.info
